#
# Copyright © 2016-2021 ThingsBoard, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  # Server bind address
  address: "HTTP_BIND_ADDRESS"
  # Server bind port
  port: "HTTP_BIND_PORT"
browser:
  # Browser launch timeout (ms)
  launchTimeout: "BROWSER_LAUNCH_TIMEOUT"
  # Default page navigation timeout (ms)
  defaultPageNavigationTimeout: "DEFAULT_PAGE_NAVIGATION_TIMEOUT"
  # Dashboard load wait time (ms)
  dashboardLoadWaitTime: "DASHBOARD_LOAD_WAIT_TIME"
logger:
  level: "LOGGER_LEVEL"
  path: "LOG_FOLDER"
  filename: "LOGGER_FILENAME"
